### ISSUE TITLE
Updated release?  Or new maintainer?

### ISSUE THREAD

**Issue by srbaker** [dsantosmerino/open-cagex#7]
Heya,

I'm using OpenCagex in two projects, and some dependencies are out of date.

I am willing to take over maintainership, if you are willing to allow me to.

Thanks!

**Comment by dsantosmerino** [comment]
Hi @srbaker!

Thanks for the heads up, I kind of forgot about this project, sorry :see_no_evil:

I already released  `v0.1.4`, updating all the dependencies and changing a bit the workflows. It should be pretty easy to keep the project updated now.

Regarding maintenance, I'm open to adding maintainers. Let me know if you have any ideas to iterate on this and if you are still interested.

BTW, Such a great honor having you here. I just read your post about the [history of RSpec](https://www.stevenrbaker.com/tech/history-of-rspec.html). I'm sure there are more tricks left in this pony, but enjoy the ride, no pressure.

**Comment by srbaker** [comment]
Heya!  Thanks!  I'm using it for a small project.  If I find I need anything, I'll open some PRs.  This project is in its early days, so we'll see where it goes.

Thanks for the kinds words.  I do struggle with that from time to time, but these days I'm just trying to enjoy creating things.
